server:
  port: 8081
spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://localhost:3306/ea
    username: root
    password: Mullerbar@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username:  essebani.anas@gmail.com 
    password: kpozlnxqmfqgkpkc

    properties:      mail:
        smtp:
          auth:  true
          starttls:
            enable:  true